"""create initial tables

Revision ID: 516aae3f1db3
Revises: 
Create Date: 2026-09-16 12:20:41.892212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '516aae3f1db3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_version_id', sa.UUID(), nullable=False),
    sa.Column('item_selector', sa.Text(), nullable=False),
    sa.Column('title_selector', sa.Text(), nullable=True),
    sa.Column('link_selector', sa.Text(), nullable=True),
    sa.Column('date_selector', sa.Text(), nullable=True),
    sa.Column('description_selector', sa.Text(), nullable=True),
    sa.Column('image_selector', sa.Text(), nullable=True),
    sa.Column('author_selector', sa.Text(), nullable=True),
    sa.Column('category_selector', sa.Text(), nullable=True),
    sa.Column('pagination_selector', sa.Text(), nullable=True),
    sa.Column('rendering_mode', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_version_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_path', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('version_major', sa.Integer(), nullable=False),
    sa.Column('version_minor', sa.Integer(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('config_path', sa.String(length=500), nullable=False),
    sa.Column('script_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('last_execution_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('refresh_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('geographic_scope', sa.String(length=20), nullable=True),
    sa.Column('publishing_volume', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('proxy_required', sa.Boolean(), nullable=False),
    sa.Column('proxy_used', sa.Boolean(), nullable=False),
    sa.Column('scraping_strategy', sa.String(length=30), nullable=True),
    sa.Column('source_from', sa.String(length=20), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('deactivation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    op.drop_table('feeds')
    op.drop_table('feed_versions')
    op.drop_table('feed_runs')
    op.drop_table('feed_configurations')
    op.drop_table('articles')
    # ### end Alembic commands ###
